### ISSUE TITLE
Option to define whether client should automatically renew token

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2client.js#49]
Currently, client creates a timer roughly equal token expiry timeout to make sure token is always up to date. In some cases this timeout is not needed (Web UI handles token renew by showing user login form) or even harmful (tests are not exiting until the timeout is cleared).

User should be able to define during client initialization whether he wants token to be renewed automatically.

**Comment by Kami** [comment]
I think having an option for auto-renew is reasonable.

As mentioned in the past, I think client should have two APIs - one where user passes in an existing token to the constructor and one where user passes in credentials (username + password).

In the second case, client should auto-renew the token, but user should be able to disable this by passing `{ auto_renew: false }` options object to the client or similar.

As far as actual implementation goes - I'm personally not a fan of timer and I think "lazy renewal" is better - on every request, check if the token is about to expire (e.g. expire_ts - 10 > now) and if it is, renew the token before proceeding with the request. That's also the approach which is used by a lot of other client libraries I'm aware of.

**Comment by enykeev** [comment]
> As mentioned in the past, I think client should have two APIs - one where user passes in an existing token to the constructor and one where user passes in credentials (username + password).

Until you make a request, there is no difference between the two so what I'm doing here is initializing client unauthenticated and then allowing user to either auth with credentials or set a token or key manually.

As for implementation, yeah, you probably right and it would remove the pain of clearing the timeout while the overhead of the check is negligible.

**Comment by enykeev** [comment]
Although instead of postponing the request I'd rather run reauth in parallel for the sake of not increasing latency.

**Comment by Kami** [comment]
It's your call - I don't think the overhead is large since it would only happen once before the token expires and tokens are quite long lived by default so this shouldn't be a problem (so latency would only be increased for a single request which again, imo, is not a big deal).
