### ISSUE TITLE
Potential security vulnerabilities in outdated dependencies

### ISSUE THREAD

**Issue by armab** [StackStorm/st2client.js#78]
`st2client.js` has a lot of security warnings in its npm dependencies located in https://github.com/StackStorm/st2client.js/blob/master/package-lock.json

(https://github.com/StackStorm/st2client.js/network/alerts)

![](https://i.imgur.com/07UNGm9.png)

We'll need to update them, making sure client functionality/tests are still working as before.

**Comment by bgaeddert** [comment]
ok I'll start working though them.
